AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*'

Documentation:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/FrozenStringLiteralComment:
  Enabled: false

EndOfLine:
  Enabled: false
