module Helpers
  RANDOM_STRING = 'elkvmw[iepohjwp'

  def no_timestamp_hash(collection)
    collection.attributes.except('created_at', 'updated_at')
  end

  module WildNothing
    def self.data
      {
        :name=>"Wild Nothing",
         :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df",
         :image=>"https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
         :lastfm_listeners_count=>499550,
         :lastfm_plays_count=>17287791,
         :tags=>["dream pop", "shoegaze", "indie pop", "indie", "seen live"],
         :description=>
          "Wild Nothing is the solo project of Virginia-born Jack Tatum. Tatum began recording under the moniker Wild Nothing in the summer of 2009 in Blacksburg, Virginia. Upon gathering attention in indie music circles, he was signed with the Captured Tracks record label and began touring with a band. His debut full-length, \"Gemini,\" was released in spring 2010 to acclaim from Pitchfork Media and the music editors at Amazon.com. A follow-up album called \"Nocturne\" was released in 2012. His second EP \"Empty Estate\" was released in May 2013. Tatum's third LP entitled \"Life of Pause\" was released on February 19, 2016.",
          :top_tracks=>
          [{:title=>"Chinatown",
            :artist=>{:name=>"Wild Nothing"},
            :lastfm_listeners_count=>189359,
            :lastfm_plays_count=>1096361,
            :mbid=>"9a74b1e7-a7a9-46fc-8ad3-58306fdac86f"},
           {:title=>"Shadow",
            :artist=>{:name=>"Wild Nothing"},
            :lastfm_listeners_count=>185592,
            :lastfm_plays_count=>1093204,
            :mbid=>"444148a3-ee43-44f3-b855-d50ea62a0bee"},
           {:title=>"Summer Holiday",
            :artist=>{:name=>"Wild Nothing"},
            :lastfm_listeners_count=>154686,
            :lastfm_plays_count=>929075,
            :mbid=>"b48a77ec-eb37-4ab0-a6d9-626d5b5aa1aa"},
           {:title=>"Live In Dreams",
            :artist=>{:name=>"Wild Nothing"},
            :lastfm_listeners_count=>154954,
            :lastfm_plays_count=>923758,
            :mbid=>"c294d6ba-7ed0-494a-94c2-2a0f8f6a68ab"},
           {:title=>"Nocturne",
            :artist=>{:name=>"Wild Nothing"},
            :lastfm_listeners_count=>123250,
            :lastfm_plays_count=>758128,
            :mbid=>"a1a28a89-2419-4d4e-af24-99038ca601cf"},
           {:title=>"Paradise",
            :artist=>{:name=>"Wild Nothing"},
            :lastfm_listeners_count=>116365,
            :lastfm_plays_count=>677931,
            :mbid=>"adfc8f42-00cb-4bff-a243-c5b85bfc35e3"},
           {:title=>"Only Heather",
            :artist=>{:name=>"Wild Nothing"},
            :lastfm_listeners_count=>99926,
            :lastfm_plays_count=>591016,
            :mbid=>"701993c0-554f-4b8a-b2a1-bf27d560a349"},
           {:title=>"Drifter",
            :artist=>{:name=>"Wild Nothing"},
            :lastfm_listeners_count=>105432,
            :lastfm_plays_count=>568857,
            :mbid=>"6a864fbe-1e58-4485-84cd-b451e786fb69"},
           {:title=>"Midnight Song",
            :artist=>{:name=>"Wild Nothing"},
            :lastfm_listeners_count=>100593,
            :lastfm_plays_count=>540748,
            :mbid=>"fbc9b4e8-5848-4af0-badb-9efe7d043d45"},
           {:title=>"Pessimist",
            :artist=>{:name=>"Wild Nothing"},
            :lastfm_listeners_count=>98008,
            :lastfm_plays_count=>492346,
            :mbid=>"284b1ad5-8b8e-4573-9884-cbc2a7c1d9b1"}],
            :top_albums=>
            [{:title=>"Gemini",
              :artist=>{:name=>"Wild Nothing"},
              :lastfm_plays_count=>6737796,
              :cover=>"https://lastfm-img2.akamaized.net/i/u/300x300/c60a738cd2244da9bc2b44b51d643602.png"},
             {:title=>"Nocturne",
              :artist=>{:name=>"Wild Nothing"},
              :lastfm_plays_count=>5766070,
              :cover=>"https://lastfm-img2.akamaized.net/i/u/300x300/3601d7b9f23e43aea6f9fa002672c6eb.png"},
             {:title=>"Life of Pause",
              :artist=>{:name=>"Wild Nothing"},
              :lastfm_plays_count=>800191,
              :cover=>"https://lastfm-img2.akamaized.net/i/u/300x300/ae54820568b7b3e42e9fe0fca2155f20.png"},
             {:title=>"Empty Estate",
              :artist=>{:name=>"Wild Nothing"},
              :lastfm_plays_count=>738127,
              :cover=>"https://lastfm-img2.akamaized.net/i/u/300x300/ee3fa5a535164e01b6f46496adb3240b.png"},
             {:title=>"Golden Haze",
              :artist=>{:name=>"Wild Nothing"},
              :lastfm_plays_count=>647461,
              :cover=>"https://lastfm-img2.akamaized.net/i/u/300x300/d0398f9a72434e60a3d0479ffbb46c68.png"},
             {:title=>"Indigo",
              :artist=>{:name=>"Wild Nothing"},
              :lastfm_plays_count=>411350,
              :cover=>"https://lastfm-img2.akamaized.net/i/u/300x300/ffe0345f1e6bb0728de877faeb1917c9.png"}],
              :similar_artists=>
              [{:name=>"Craft Spells",
              :mbid=>"d3afff73-119e-406e-8551-9403e80c531b",
              :image=>"https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
              :lastfm_listeners_count=>278796,
              :lastfm_plays_count=>4732209,
              :tags=>["dream pop", "indie pop", "indie", "Lo-Fi", "electronic"],
              :description=>
               "After a dormant period following the release of the Gallery EP in 2012, Craft Spells’ Justin Vallesteros is back with the gorgeously ambitious Nausea. It’s Craft Spells’ second proper full length LP, and first since 2010′s critically acclaimed Idle Labor.\nSince last on the radar, Justin moved to San Francisco to find a niche in the Bay Area music scene. This proved difficult within the regarded garage rock scene and insular DJ night crowds currently dominating the area’s music community. Here, Justin fell into a slump, creatively. With a severe bout of writer’s block he retreated to his parent’s house in Lathrop, CA. Away from the city, he put down his guitar for a full year in favor of properly training himself on piano, the instrument from which all the tracks for Nausea were written.\nBeing in limbo between the city and the suburbs, Justin felt actual nausea, added to by his admitted semi-addiction to social media and quickly found himself disillusioned. Vallesteros unplugged from that world as much as possible and completely immersed himself in the music (Emmit Rhodes and the solo works of Yellow Magic Orchestra’s Haroumi Hosono and Yukihiro Takahashi) and writing (the works of Mishima, for one) that would come to form the LP.\nThe demos came together in early 2014 and Vallesteros flew to Seattle to produce  the record with engineer Dylan Wall. Teaming up on the recording with Craft Spells stalwarts Javier Suarez and Andy Lum, the band went into the studio and recorded a whole and complete work, full of ideas and a new found maturity in both songwriting and recording sophistication. Within the first few seconds of lead single “Breaking the Angle Against the Tide” we know we’re not listening to the same Craft Spells anymore. This is a bold, beautiful and lush new sound emphasizing the songwriting abilities Vallesteros always had. An album highlighted by loads of piano, real strings and acoustic guitar, this change is like the color coming alive in the Wizard of Oz. The beautiful “Komorebi” with it’s piano chord progression and sorrowful string accompaniment emphasizes this newfound maturity and confidence as a writer that is the next logical step in Craft Spells’ career."},
             {:name=>"DIIV",
              :mbid=>"b5ff61dd-0154-4e80-b46b-c733f87db602",
              :image=>"https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
              :lastfm_listeners_count=>378082,
              :lastfm_plays_count=>12222063,
              :tags=>["shoegaze", "dream pop", "Lo-Fi", "psychedelic", "seen live"],
              :description=>
               "DIIV (previously known as Dive) is the ongoing project of  Zachary Cole Smith, who has already made a name for himself in the New York music scene playing for bands such as Beach Fossils,  Darwin Deez and  Soft Black. Smith formed DIIV in Brooklyn in 2011 as his solo project, but soon put together a live band with  Devin Ruben Perez, his childhood friend  Andrew Bailey, and ex-Smith Westerns drummer Colby Hewitt. DIIV's first release, the single Sometime , was released as 7\" on Captured Tracks on Oct. 11th, 2011. The debut album Oshin was released in June 2012.\n\nDrummer Colby Hewitt left the band in spring 2015 due to his drug addiction.[17] Ben Newman (from North Carolina, formerly of Banda Suki) was added as the group's drummer in 2015. Their upcoming album, Is the Is Are, is set to be released in 2016, on February 5th."},
             {:name=>"Beach Fossils",
              :mbid=>"3df3818e-7984-4c62-bee3-81f95f8c6651",
              :image=>"https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
              :lastfm_listeners_count=>433484,
              :lastfm_plays_count=>14043381,
              :tags=>["Lo-Fi", "indie", "surf rock", "Garage Rock", "noise pop"],
              :description=>
               "Beach Fossils is an American indie rock band from Brooklyn, New York, formed in 2009. The group currently includes Dustin Payseur, Tommy Gardner, Jack Doyle Smith and Tommy Davidson. They are known for their lo-fi, atmospheric sound and Payseur's vocal style.\n\nFormed in 2009, the act was originally a means to expand the solo project of Dustin Payseur. That same year bassist John Peña and guitarist Christopher Burke were recruited as the lineup for their initial tour. Their debut single, Daydream/Desert Sand was released in February 2010 on Captured Tracks. In May 2010, their self-titled debut album was released, met with favorable reviews.\nThe following years saw a number of changes to their lineup, including when John Peña left the band in 2011 to form Heavenly Beat, and guitarist Cole Smith, who left for his solo project, DIIV. In 2012, Tommy Gardner stepped in as the drummer to form their current lineup. Clash the Truth was released in early 2013, peaking at number 40 on the Independent Albums chart. Paysuer described it as being an album about what happens after you've solved the immediate problems that come with moving away from home - \"something that just doesn't feel like it makes sense yet\"."},
               {:name=>"Real Estate",
                :mbid=>"2ff0dfc6-0542-4bbc-a44a-60605c074ba6",
                :image=>"https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
                :lastfm_listeners_count=>631510,
                :lastfm_plays_count=>20250143,
                :tags=>["Lo-Fi", "indie", "seen live", "surf rock", "Surf"],
                :description=>
                 "Real Estate is a band from Ridgewood, New Jersey, United States, now based in Brooklyn, N.Y. The band has roots in the Garden State and they’re led by singer/guitarist Martin Courtney and feature guitarist Matthew Mondanile (the latter known to some for his work in Ducktails, Predator Vision, and The Parasails) as well as Alex Bleeker (side project: Alex Bleeker And The Freaks) on bass and Etienne Duguay (also of Predator Vision) on the drums. They started in 2009 and in 2011 Jackson Pollis replaced Etienne on drums and Jonah Maurer joined the band on keys and guitar. In 2013, Matt Kallman, formerly of Girls, replaced Jonah Maurer on keys."},
               {:name=>"Washed Out",
                :mbid=>"74a30f2a-dae6-4e99-8a75-cb0f93b31aa6",
                :image=>"https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
                :lastfm_listeners_count=>775462,
                :lastfm_plays_count=>24737682,
                :tags=>["chillwave", "electronic", "Lo-Fi", "chillout", "seen live"],
                :description=>
                 "Washed Out is Ernest Greene, a young guy from Perry, Georgia, USA who makes bedroom synthpop that sounds blurred and woozily evocative.\n\nThere’s a sense of longing and distance in Greene’s somber, filtered vocals, but it’s what he does compositionally that makes Washed Out stand out. Backed by gently pulsing, Balearic-tinged disco, Greene’s voice takes on a new dimension. Reminiscent of groups like The Glass and Chromatics, Washed Out is the music to end your night with, when the city is quiet and you've got a long walk home ahead of you.\n\n2009\n\nWashed Out track \"Feel It Around\" is the famous introduction and theme song to IFC's television series \"Portlandia\".  (added 2014)"},
               {:name=>"Small Black",
                :mbid=>"94c9f694-21b6-4b24-9722-4ea18f75f8e1",
                :image=>"https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
                :lastfm_listeners_count=>319822,
                :lastfm_plays_count=>4755021,
                :tags=>["chillwave", "Lo-Fi", "electronic", "indie", "indie pop"],
                :description=>
                 "Small Black is an electronic band from Brooklyn, New York. Their Small Black EP and debut full-length, New Chain, were released on JagJaguwar. \n\nThey recently released the Moon Killer Mixtape as a free download on their Soundcloud page.\n\nGET THE MIXTAPE HERE::\nhttp://www.small-black.com"}]
      }
    end

    def self.persisted_data
      {
        "id"=>1,
         "name"=>"Wild Nothing",
         "image"=>"https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
         "mbid"=>"a181595e-5b84-4439-a5f4-f548ddfb64df",
         "description"=>
          "Wild Nothing is the solo project of Virginia-born Jack Tatum. Tatum began recording under the moniker Wild Nothing in the summer of 2009 in Blacksburg, Virginia. Upon gathering attention in indie music circles, he was signed with the Captured Tracks record label and began touring with a band. His debut full-length, \"Gemini,\" was released in spring 2010 to acclaim from Pitchfork Media and the music editors at Amazon.com. A follow-up album called \"Nocturne\" was released in 2012. His second EP \"Empty Estate\" was released in May 2013. Tatum's third LP entitled \"Life of Pause\" was released on February 19, 2016.",
         "lastfm_listeners_count"=>499550,
         "lastfm_plays_count"=>17287791,
         "listeners_count"=>0,
         "plays_count"=>0,
         "similar_artist_ids"=>[2, 3, 4, 5, 6, 7],
         "tag_ids"=>[1, 2, 3, 4, 5],
         "top_track_ids"=>[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
         "top_album_ids"=>[1, 2, 3, 4, 5, 6],
        }
    end

    class Nocturne
      def self.data
        {
          :title=>"Nocturne",
           :artist=>{:name=>"Wild Nothing"},
           :lastfm_listeners_count=>229379,
           :lastfm_plays_count=>5766070,
           :description=>
            "Nocturne is the second studio album by American dream pop act Wild Nothing, released on August 28, 2012 on Captured Tracks.\n\nThe success of Wild Nothing's debut allowed Jack Tatum to record in a full studio for its follow-up, a change of pace from Gemini's exclusive use of the laptop for recording. Working with producer Nicolas Vernhes, Tatum stated: “The biggest thing was just having a producer, having somebody extremely knowledgeable to work with. I mean, obviously I had a lot of nice equipment at my disposal for the first time, too ... But I never wanted to use any of that to pursue a wholly different sound to the first album; it was just nice to have somebody to bounce ideas off, to help me tweak things.” \"Shadow,\" the first song from Nocturne to be released, features a string section, something Tatum \"never\" could have done without a studio environment",
           :cover=>"https://lastfm-img2.akamaized.net/i/u/300x300/3601d7b9f23e43aea6f9fa002672c6eb.png",
           :release_date=>"2012-01-01",
           :release_type=>"Album",
           :bandcamp_link=>nil,
           :tags=>["2012", "dream pop", "best of 2012", "indie", "favorite albums"],
           :labels=>["Captured Tracks"],
           :tracks=>
            [{:title=>"Shadow",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>258,
              :bandcamp_link=>nil},
             {:title=>"Midnight Song",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>185,
              :bandcamp_link=>nil},
             {:title=>"Nocturne",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>318,
              :bandcamp_link=>nil},
             {:title=>"Through the Grass",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>267,
              :bandcamp_link=>nil},
             {:title=>"Only Heather",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>193,
              :bandcamp_link=>nil},
             {:title=>"This Chain Won’t Break",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>218,
              :bandcamp_link=>nil},
             {:title=>"Disappear Always",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>209,
              :bandcamp_link=>nil},
             {:title=>"Paradise",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>330,
              :bandcamp_link=>nil},
             {:title=>"Counting Days",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>231,
              :bandcamp_link=>nil},
             {:title=>"The Blue Dress",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>207,
              :bandcamp_link=>nil},
             {:title=>"Rheya",
              :artist=>{:name=>"Wild Nothing", :mbid=>"a181595e-5b84-4439-a5f4-f548ddfb64df"},
              :duration=>235,
              :bandcamp_link=>nil}]
          }
      end

      def self.persisted_data
        {
          "id"=>1,
           "title"=>"Nocturne",
           "artist_id"=>1,
           "cover"=>"https://lastfm-img2.akamaized.net/i/u/300x300/3601d7b9f23e43aea6f9fa002672c6eb.png",
           "mbid"=>nil,
           "description"=>
            "Nocturne is the second studio album by American dream pop act Wild Nothing, released on August 28, 2012 on Captured Tracks.\n\nThe success of Wild Nothing's debut allowed Jack Tatum to record in a full studio for its follow-up, a change of pace from Gemini's exclusive use of the laptop for recording. Working with producer Nicolas Vernhes, Tatum stated: “The biggest thing was just having a producer, having somebody extremely knowledgeable to work with. I mean, obviously I had a lot of nice equipment at my disposal for the first time, too ... But I never wanted to use any of that to pursue a wholly different sound to the first album; it was just nice to have somebody to bounce ideas off, to help me tweak things.” \"Shadow,\" the first song from Nocturne to be released, features a string section, something Tatum \"never\" could have done without a studio environment",
           "release_date"=>"2012-01-01",
           "format"=>nil,
           "bandcamp_link"=>nil,
           "lastfm_listeners_count"=>229379,
           "listeners_count"=>0,
           "lastfm_plays_count"=>5766070,
           "plays_count"=>0,
           "label_ids"=>[1],
           "tag_ids"=>[1, 2, 3, 4, 5],
           "track_ids"=>[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
           "official"=>false
          }
      end
    end

    class Chinatown
      def self.track_data
        {:track => {:album=>{:artist=>{:name=>"Wild Nothing"}, :cover=>"https://lastfm-img2.akamaized.net/i/u/600x600/c60a738cd2244da9bc2b44b51d643602.png", :mbid=>"98174762-4674-4382-827f-db7248c4806c", :title=>"Gemini"}, :artist=>{:name=>"Wild Nothing"}, :duration=>199, :lastfm_listeners_count=>189944, :lastfm_plays_count=>1099980, :mbid=>"9a74b1e7-a7a9-46fc-8ad3-58306fdac86f", :tags=>["dream pop", "indie", "chillwave", "shoegaze", "electronica"], :title=>"Chinatown", :wiki=>nil}}
      end

      def self.muffon_track_data
        {:track => {:album=>{:artist=>{:name=>"Wild Nothing"}, :cover=>"https://lastfm-img2.akamaized.net/i/u/600x600/c60a738cd2244da9bc2b44b51d643602.png", :mbid=>"98174762-4674-4382-827f-db7248c4806c", :title=>"Gemini"}, :artist=>{:name=>"Wild Nothing"}, :duration=>199, :lastfm_listeners_count=>189944, :lastfm_plays_count=>1099980, :mbid=>"9a74b1e7-a7a9-46fc-8ad3-58306fdac86f", :tags=>["dream pop", "indie", "chillwave", "shoegaze", "electronica"], :title=>"Chinatown", :vk_id=>"371745449_456491618_223d081ac8d84ebb17_b5faa65c1559a8b1b6", :wiki=>nil, :youtube_link=>"https://www.youtube.com/embed/j6tZLVoAQnM?rel=0"}}
      end

      def self.persisted_data
        {"album_ids" => [1],
          "artist_id" => 1,
          "bandcamp_link" => nil,
          "duration" => 199,
          "id" => 1,
          "lastfm_listeners_count" => 189944,
          "lastfm_plays_count" => 1099980,
          "listeners_count" => 0,
          "mbid" => "9a74b1e7-a7a9-46fc-8ad3-58306fdac86f",
          "plays_count" => 0,
          "tag_ids" => [1, 2, 3, 4, 5],
          "title" => "Chinatown",
          "vk_id" => "371745449_456491618_223d081ac8d84ebb17_b5faa65c1559a8b1b6",
          "vk_link" => nil,
          "wiki" => nil,
          "youtube_link" => 'https://www.youtube.com/embed/j6tZLVoAQnM?rel=0'}
      end
    end
  end

  class Search
    def self.persisted_data
      {
        albums:
          [{"id"=>1,
            "title"=>"Nocturne",
            "cover"=>"https://lastfm-img2.akamaized.net/i/u/300x300/3601d7b9f23e43aea6f9fa002672c6eb.png",
            "artist_id"=>1,
            "mbid"=>nil,
            "description"=>nil,
            "release_date"=>nil,
            "format"=>nil,
            "bandcamp_link"=>nil,
            "lastfm_listeners_count"=>0,
            "listeners_count"=>0,
            "lastfm_plays_count"=>0,
            "plays_count"=>0,
            "label_ids"=>[],
            "tag_ids"=>[],
            "track_ids"=>[],
            "official"=>false},
           {"id"=>2,
            "title"=>"Gemini",
            "cover"=>"https://lastfm-img2.akamaized.net/i/u/300x300/c60a738cd2244da9bc2b44b51d643602.png",
            "artist_id"=>1,
            "mbid"=>nil,
            "description"=>nil,
            "release_date"=>nil,
            "format"=>nil,
            "bandcamp_link"=>nil,
            "lastfm_listeners_count"=>0,
            "listeners_count"=>0,
            "lastfm_plays_count"=>0,
            "plays_count"=>0,
            "label_ids"=>[],
            "tag_ids"=>[],
            "track_ids"=>[],
            "official"=>false},
           {"id"=>3,
            "title"=>"Life of Pause",
            "cover"=>"https://lastfm-img2.akamaized.net/i/u/300x300/ae54820568b7b3e42e9fe0fca2155f20.png",
            "artist_id"=>1,
            "mbid"=>nil,
            "description"=>nil,
            "release_date"=>nil,
            "format"=>nil,
            "bandcamp_link"=>nil,
            "lastfm_listeners_count"=>0,
            "listeners_count"=>0,
            "lastfm_plays_count"=>0,
            "plays_count"=>0,
            "label_ids"=>[],
            "tag_ids"=>[],
            "track_ids"=>[],
            "official"=>false},
           {"id"=>4,
            "title"=>"Empty Estate",
            "cover"=>"https://lastfm-img2.akamaized.net/i/u/300x300/ee3fa5a535164e01b6f46496adb3240b.png",
            "artist_id"=>1,
            "mbid"=>nil,
            "description"=>nil,
            "release_date"=>nil,
            "format"=>nil,
            "bandcamp_link"=>nil,
            "lastfm_listeners_count"=>0,
            "listeners_count"=>0,
            "lastfm_plays_count"=>0,
            "plays_count"=>0,
            "label_ids"=>[],
            "tag_ids"=>[],
            "track_ids"=>[],
            "official"=>false},
           {"id"=>5,
            "title"=>"Golden Haze",
            "cover"=>"https://lastfm-img2.akamaized.net/i/u/300x300/d0398f9a72434e60a3d0479ffbb46c68.png",
            "artist_id"=>1,
            "mbid"=>nil,
            "description"=>nil,
            "release_date"=>nil,
            "format"=>nil,
            "bandcamp_link"=>nil,
            "lastfm_listeners_count"=>0,
            "listeners_count"=>0,
            "lastfm_plays_count"=>0,
            "plays_count"=>0,
            "label_ids"=>[],
            "tag_ids"=>[],
            "track_ids"=>[],
            "official"=>false},
           {"id"=>6,
            "title"=>"Indigo",
            "cover"=>"https://lastfm-img2.akamaized.net/i/u/300x300/ffe0345f1e6bb0728de877faeb1917c9.png",
            "artist_id"=>1,
            "mbid"=>nil,
            "description"=>nil,
            "release_date"=>nil,
            "format"=>nil,
            "bandcamp_link"=>nil,
            "lastfm_listeners_count"=>0,
            "listeners_count"=>0,
            "lastfm_plays_count"=>0,
            "plays_count"=>0,
            "label_ids"=>[],
            "tag_ids"=>[],
            "track_ids"=>[],
            "official"=>false}],
        artists:
          [{"id"=>1,
            "name"=>"Wild Nothing",
            "image"=>"https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
            "lastfm_listeners_count"=>499550,
            "mbid"=>nil,
            "description"=>nil,
            "lastfm_plays_count"=>0,
            "listeners_count"=>0,
            "plays_count"=>0,
            "similar_artist_ids"=>[],
            "tag_ids"=>[],
            "top_track_ids"=>[],
            "top_album_ids"=>[]},
           {"id"=>2,
            "name"=>"Wild_Nothing",
            "image"=>nil,
            "lastfm_listeners_count"=>736,
            "mbid"=>nil,
            "description"=>nil,
            "lastfm_plays_count"=>0,
            "listeners_count"=>0,
            "plays_count"=>0,
            "similar_artist_ids"=>[],
            "tag_ids"=>[],
            "top_track_ids"=>[],
            "top_album_ids"=>[]},
           {"id"=>3,
            "name"=>"Wild Belle (Feat. Notorious B.I.G.)",
            "image"=>nil,
            "lastfm_listeners_count"=>716,
            "mbid"=>nil,
            "description"=>nil,
            "lastfm_plays_count"=>0,
            "listeners_count"=>0,
            "plays_count"=>0,
            "similar_artist_ids"=>[],
            "tag_ids"=>[],
            "top_track_ids"=>[],
            "top_album_ids"=>[]},
           {"id"=>4,
            "name"=>"Wild Nothing //",
            "image"=>nil,
            "lastfm_listeners_count"=>198,
            "mbid"=>nil,
            "description"=>nil,
            "lastfm_plays_count"=>0,
            "listeners_count"=>0,
            "plays_count"=>0,
            "similar_artist_ids"=>[],
            "tag_ids"=>[],
            "top_track_ids"=>[],
            "top_album_ids"=>[]},
           {"id"=>5,
            "name"=>"The Wild Northern",
            "image"=>"https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png",
            "lastfm_listeners_count"=>193,
            "mbid"=>nil,
            "description"=>nil,
            "lastfm_plays_count"=>0,
            "listeners_count"=>0,
            "plays_count"=>0,
            "similar_artist_ids"=>[],
            "tag_ids"=>[],
            "top_track_ids"=>[],
            "top_album_ids"=>[]},
           {"id"=>6,
            "name"=>"Wild Notes",
            "image"=>nil,
            "lastfm_listeners_count"=>122,
            "mbid"=>nil,
            "description"=>nil,
            "lastfm_plays_count"=>0,
            "listeners_count"=>0,
            "plays_count"=>0,
            "similar_artist_ids"=>[],
            "tag_ids"=>[],
            "top_track_ids"=>[],
            "top_album_ids"=>[]}],
        tracks: 
          [{"id"=>1,
          "title"=>"Chinatown",
          "lastfm_listeners_count"=>189359,
          "artist_id"=>1,
          "mbid"=>nil,
          "duration"=>nil,
          "bandcamp_link"=>nil,
          "vk_link"=>nil,
          "vk_id"=>nil,
          "youtube_link"=>nil,
          "lastfm_plays_count"=>0,
          "listeners_count"=>0,
          "plays_count"=>0,
          "tag_ids"=>[],
          "wiki"=>nil,
          "album_ids"=>[]},
         {"id"=>2,
          "title"=>"Shadow",
          "lastfm_listeners_count"=>185592,
          "artist_id"=>1,
          "mbid"=>nil,
          "duration"=>nil,
          "bandcamp_link"=>nil,
          "vk_link"=>nil,
          "vk_id"=>nil,
          "youtube_link"=>nil,
          "lastfm_plays_count"=>0,
          "listeners_count"=>0,
          "plays_count"=>0,
          "tag_ids"=>[],
          "wiki"=>nil,
          "album_ids"=>[]},
         {"id"=>3,
          "title"=>"Live In Dreams",
          "lastfm_listeners_count"=>154954,
          "artist_id"=>1,
          "mbid"=>nil,
          "duration"=>nil,
          "bandcamp_link"=>nil,
          "vk_link"=>nil,
          "vk_id"=>nil,
          "youtube_link"=>nil,
          "lastfm_plays_count"=>0,
          "listeners_count"=>0,
          "plays_count"=>0,
          "tag_ids"=>[],
          "wiki"=>nil,
          "album_ids"=>[]},
         {"id"=>4,
          "title"=>"Summer Holiday",
          "lastfm_listeners_count"=>154686,
          "artist_id"=>1,
          "mbid"=>nil,
          "duration"=>nil,
          "bandcamp_link"=>nil,
          "vk_link"=>nil,
          "vk_id"=>nil,
          "youtube_link"=>nil,
          "lastfm_plays_count"=>0,
          "listeners_count"=>0,
          "plays_count"=>0,
          "tag_ids"=>[],
          "wiki"=>nil,
          "album_ids"=>[]},
         {"id"=>5,
          "title"=>"Nocturne",
          "lastfm_listeners_count"=>123250,
          "artist_id"=>1,
          "mbid"=>nil,
          "duration"=>nil,
          "bandcamp_link"=>nil,
          "vk_link"=>nil,
          "vk_id"=>nil,
          "youtube_link"=>nil,
          "lastfm_plays_count"=>0,
          "listeners_count"=>0,
          "plays_count"=>0,
          "tag_ids"=>[],
          "wiki"=>nil,
          "album_ids"=>[]},
         {"id"=>6,
          "title"=>"Paradise",
          "lastfm_listeners_count"=>116365,
          "artist_id"=>1,
          "mbid"=>nil,
          "duration"=>nil,
          "bandcamp_link"=>nil,
          "vk_link"=>nil,
          "vk_id"=>nil,
          "youtube_link"=>nil,
          "lastfm_plays_count"=>0,
          "listeners_count"=>0,
          "plays_count"=>0,
          "tag_ids"=>[],
          "wiki"=>nil,
          "album_ids"=>[]},
         {"id"=>7,
          "title"=>"Drifter",
          "lastfm_listeners_count"=>105432,
          "artist_id"=>1,
          "mbid"=>nil,
          "duration"=>nil,
          "bandcamp_link"=>nil,
          "vk_link"=>nil,
          "vk_id"=>nil,
          "youtube_link"=>nil,
          "lastfm_plays_count"=>0,
          "listeners_count"=>0,
          "plays_count"=>0,
          "tag_ids"=>[],
          "wiki"=>nil,
          "album_ids"=>[]},
         {"id"=>8,
          "title"=>"Midnight Song",
          "lastfm_listeners_count"=>100593,
          "artist_id"=>1,
          "mbid"=>nil,
          "duration"=>nil,
          "bandcamp_link"=>nil,
          "vk_link"=>nil,
          "vk_id"=>nil,
          "youtube_link"=>nil,
          "lastfm_plays_count"=>0,
          "listeners_count"=>0,
          "plays_count"=>0,
          "tag_ids"=>[],
          "wiki"=>nil,
          "album_ids"=>[]},
         {"id"=>9,
          "title"=>"Only Heather",
          "lastfm_listeners_count"=>99926,
          "artist_id"=>1,
          "mbid"=>nil,
          "duration"=>nil,
          "bandcamp_link"=>nil,
          "vk_link"=>nil,
          "vk_id"=>nil,
          "youtube_link"=>nil,
          "lastfm_plays_count"=>0,
          "listeners_count"=>0,
          "plays_count"=>0,
          "tag_ids"=>[],
          "wiki"=>nil,
          "album_ids"=>[]},
         {"id"=>10,
          "title"=>"Disappear Always",
          "lastfm_listeners_count"=>81445,
          "artist_id"=>1,
          "mbid"=>nil,
          "duration"=>nil,
          "bandcamp_link"=>nil,
          "vk_link"=>nil,
          "vk_id"=>nil,
          "youtube_link"=>nil,
          "lastfm_plays_count"=>0,
          "listeners_count"=>0,
          "plays_count"=>0,
          "tag_ids"=>[],
          "wiki"=>nil,
          "album_ids"=>[]}]
      }
    end
  end

  class Radio
    def self.sample_track
      {:title=>"A Threaded Needle",
       :artist=>{:name=>"Lotus Plaza"},
       :lastfm_listeners_count=>15968,
       :lastfm_plays_count=>68157,
       :mbid=>"fe93d89a-35a2-4d17-b144-1df9bc55745a"}
    end

    def self.artist_image
      'https://lastfm-img2.akamaized.net/i/u/600x600/c097f2f6afd64ce1bf902decd73f6095'
    end

    def self.artist_track_data
      {:track => {:artist=>{:image=>"https://lastfm-img2.akamaized.net/i/u/600x600/c097f2f6afd64ce1bf902decd73f6095", :name=>"Lotus Plaza"}, :lastfm_listeners_count=>15968, :lastfm_plays_count=>68157, :link=>"https://psv4.vkuseraudio.net/c536106/u9255834/audios/b178c444c699.mp3?extra=E-LS21KVAaHRzY6QCni6TwKPgc5gRN3VSuDsFQQtyXlMPZuHvs6JyS1U6J-N_sQ442y5_IuCItVaXiiRXQJ6621tIdcZOonDEdB7rBdaT1LfqhZ-ZGIIJhg4i7q_kRdorlPIMTR8lXKXX9iAuxFml7GlTCk", :radio_artist=>{:name=>"Wild Nothing"}, :title=>"A Threaded Needle", :youtube_link=>nil}}
    end

    def self.tag_track_data
      {:track => {:artist=>{:image=>"https://lastfm-img2.akamaized.net/i/u/600x600/c097f2f6afd64ce1bf902decd73f6095", :name=>"Lotus Plaza"}, :lastfm_listeners_count=>15968, :lastfm_plays_count=>68157, :link=>"https://psv4.vkuseraudio.net/c536106/u9255834/audios/b178c444c699.mp3?extra=E-LS21KVAaHRzY6QCni6TwKPgc5gRN3VSuDsFQQtyXlMPZuHvs6JyS1U6J-N_sQ442y5_IuCItVaXiiRXQJ6621tIdcZOonDEdB7rBdaT1LfqhZ-ZGIIJhg4i7q_kRdorlPIMTR8lXKXX9iAuxFml7GlTCk", :radio_tag=>{:name=>"Dream pop music"}, :title=>"A Threaded Needle", :youtube_link=>nil}}
    end
  end
end
