# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 75
  timeout: 5000
  database: muffon
  user: muffon
  password: 1q2w3e4r5t6y

development:
  <<: *default

production:
  <<: *default