# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a51599eb332a6b219c2e637e4f940511624841d05d4a8b4423dffa3f84eb15b82b265e67434151795ef209c6203a98f7ad1bec83d9e1b93a10a20d5e9f82f868

test:
  secret_key_base: 644e0aac697508c94dd9fdd38e1e0f704d882afd6818b4b38d2605c971e151943be2341bc347fcb0277cb47439b4ee7c7279fd344949e13f616df8cd21a8bb11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
